SELECT FIELD_MAP_1
FROM MAPPING_VALUE
WHERE FIELD_TO_BE_DERIVED = 'PRODUCT_FIELD_MAPPING'
  AND INTERFACE_FILE = 'MAJESCO'
  AND TRUNC(EFFECTIVE_DATE) = TO_DATE('01-JUL-2024', 'DD-MON-YYYY')
  AND ACTIVE = 'A'
  AND FIELD_MAP_1 IS NOT NULL; 
